### ISSUE TITLE
Not Working on XCode 7

### ISSUE THREAD

**Issue by ghost** [szymonkaliski/EEG2OSC#2]
Hey man,

This isn't compiling on XCode 7. Gave me a bunch of errors about the libraries not being found. 
"ld: library not found for -ledk_ultils_mac
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

But I fixed that by deleting and reimporting the three libraries. Now it's giving me

"ld: symbol(s) not found for architecture x86_64"

You will truly be a life saver if you solve this. 
<img width="578" alt="screen shot 2016-06-16 at 2 14 55 pm" src="https://cloud.githubusercontent.com/assets/17551703/16133456/bef274c4-33cc-11e6-9628-3212db8b60df.png">

**Comment by szymonkaliski** [comment]
Hey, honestly I have no idea, it seems that something in Emotiv SDK might have changed, you might need to dig around their docs. Also, do you have the "premium" version? It's the only one supporting RAW EEG data as far as I remember.

Sorry I'm not much of a help, I made this long time ago for a project, and didn't touch it since then.

**Comment by ghost** [comment]
Thank you for the reply,

Unfortunately it was exactly what I thought it'd be. I've messed around with the new SDK but I don't have  a Premium Epoc. I'll keep trying. I'm sure there's a way to get data from the Epoc to Processing.

Appreciate your response
